# Generated by Django 5.0.1 on 2024-01-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ommoprettyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Bridal'), (2, 'Fashion')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(max_length=100, verbose_name='makeup_Detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='makeup_type'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
